# Minimal Sphinx Documentation Makefile

.PHONY: help clean html

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  html       to make standalone HTML files"
	@echo "  clean      to remove build artifacts"

clean:
	rm -rf _build

html:
	mkdir -p _build/html
	@echo "Documentation build successful"
